/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pointofsales.swing.reports;

import com.pointofsales.config.database.ConfigDB;
import java.awt.BorderLayout;
import java.sql.Connection;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author Sergey Dmitriev
 */
public class RptManager extends javax.swing.JDialog {

    /**
     * Creates new form RptJual
     *
     * @param parent
     * @param modal
     */
    public RptManager(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnUmum = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jButton1.setText("Ok");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        pnUmum.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pnUmum.setName("pnUmum"); // NOI18N

        org.jdesktop.layout.GroupLayout pnUmumLayout = new org.jdesktop.layout.GroupLayout(pnUmum);
        pnUmum.setLayout(pnUmumLayout);
        pnUmumLayout.setHorizontalGroup(
            pnUmumLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1131, Short.MAX_VALUE)
        );
        pnUmumLayout.setVerticalGroup(
            pnUmumLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 518, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Admin", pnUmum);

        jPanel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1131, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 518, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Pelanggan/Member", jPanel1);

        jPanel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1131, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 518, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Kasir", jPanel2);

        jPanel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1150, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 518, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Supplier", jPanel3);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTabbedPane1)
                    .add(layout.createSequentialGroup()
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jTabbedPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showAllReport();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnUmum;
    // End of variables declaration//GEN-END:variables

    private void RptStockItem() {
        try {
            Connection conn = new ConfigDB().getConnection();
            pnUmum.removeAll();
            pnUmum.repaint();
            pnUmum.revalidate();
            String sql = "SELECT Sales.SaleID,Sales.SaleDate,SalesDetail.ProductID,Products.ProdName AS Product,"
                    + "Products.Stock AS First,Products.StockIn AS StockIn,Products.StockOut AS StockOut FROM `Sales` "
                    + "INNER JOIN SalesDetail ON Sales.SaleID = SalesDetail.SaleID INNER JOIN Products ON SalesDetail.ProductID = Products.ProductID "
                    + "ORDER BY Sales.SaleDate ASC";
            JRDesignQuery jQuery = new JRDesignQuery();
            jQuery.setText(sql);
            JasperDesign jDesign = JRXmlLoader.load(System.getProperty("user.dir") + "/src/com/resources/jrxml/RptStockBarang.jrxml");
            jDesign.setQuery(jQuery);
            JasperReport jReport = JasperCompileManager.compileReport(jDesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, conn);
            JRViewer jView = new JRViewer(jPrint);
            pnUmum.setLayout(new BorderLayout());
            jView.setFitPageZoomRatio();
            jView.setFont(new java.awt.Font("Arial", 0, 14));
            pnUmum.add(jView);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Pada:\n" + ex.toString(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void RptStockLimit() {
        try {
            Connection conn = new ConfigDB().getConnection();
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            String sql = "SELECT `ProdName`,`SellPrice`,`CostPrice`,`Netto`,`Stock`,ProdUnit.UnitName AS Unit FROM `Products` "
                    + "INNER JOIN ProdUnit ON Products.UnitID = ProdUnit.UnitID WHERE `Stock` <5";
            JRDesignQuery jQuery = new JRDesignQuery();
            jQuery.setText(sql);
            JasperDesign jDesign = JRXmlLoader.load(System.getProperty("user.dir") + "/src/com/resources/jrxml/RptStokBarangLimit.jrxml");
            jDesign.setQuery(jQuery);
            JasperReport jReport = JasperCompileManager.compileReport(jDesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, conn);
            JRViewer jView = new JRViewer(jPrint);
            jPanel1.setLayout(new BorderLayout());
            jView.setFitPageZoomRatio();
            jView.setFont(new java.awt.Font("Arial", 0, 14));
            jPanel1.add(jView);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Pada:\n" + ex.toString(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void RptStockOver() {
        try {
            Connection conn = new ConfigDB().getConnection();
            jPanel2.removeAll();
            jPanel2.repaint();
            jPanel2.revalidate();
            String sql = "SELECT `ProdName`,`SellPrice`,`CostPrice`,`Netto`,`Stock`,ProdUnit.UnitName AS Unit "
                    + "FROM `Products` INNER JOIN ProdUnit ON Products.UnitID = ProdUnit.UnitID WHERE `Stock` >50";
            JRDesignQuery jQuery = new JRDesignQuery();
            jQuery.setText(sql);
            JasperDesign jDesign = JRXmlLoader.load(System.getProperty("user.dir") + "/src/com/resources/jrxml/RptStokBarangOver.jrxml");
            jDesign.setQuery(jQuery);
            JasperReport jReport = JasperCompileManager.compileReport(jDesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, conn);
            JRViewer jView = new JRViewer(jPrint);
            jPanel2.setLayout(new BorderLayout());
            jView.setFitPageZoomRatio();
            jView.setFont(new java.awt.Font("Arial", 0, 14));
            jPanel2.add(jView);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Pada:\n" + ex.toString(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void showAllReport() {
        RptStockItem();
        RptStockLimit();
        RptStockOver();
    }
}
