/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pointofsales.swing.reports;

import com.pointofsales.config.database.ConfigDB;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JRViewer;

/**
 *
 * @author Sergey Dmitriev
 */
public class RptProductStock extends javax.swing.JDialog {

    /**
     * Creates new form RptJual
     *
     * @param parent
     * @param modal
     */
    public RptProductStock(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnUmum = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jButton1.setText("Ok");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTabbedPane1.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        pnUmum.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pnUmum.setName("pnUmum"); // NOI18N

        org.jdesktop.layout.GroupLayout pnUmumLayout = new org.jdesktop.layout.GroupLayout(pnUmum);
        pnUmum.setLayout(pnUmumLayout);
        pnUmumLayout.setHorizontalGroup(
            pnUmumLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1131, Short.MAX_VALUE)
        );
        pnUmumLayout.setVerticalGroup(
            pnUmumLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 525, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Stok Barang", pnUmum);

        jPanel5.setName("jPanel5"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1150, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 525, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Produk Per-Satuan", jPanel5);

        jPanel6.setName("jPanel6"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1150, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 525, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Produk Per-Supplier", jPanel6);

        jPanel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1131, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 525, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Stok Barang Limit", jPanel1);

        jPanel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1131, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 525, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Stok Barang Over", jPanel2);

        jPanel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel3.setName("jPanel3"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1150, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 525, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Stok Barang Expired", jPanel3);

        jPanel4.setName("jPanel4"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 1150, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 525, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Price List", jPanel4);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(15, 15, 15)
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jTabbedPane1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showAllReport();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnUmum;
    // End of variables declaration//GEN-END:variables

    private void RptStockItem() {
        try {
            pnUmum.removeAll();
            pnUmum.repaint();
            pnUmum.revalidate();
            String sql = "SELECT `ProdName`,`SellPrice`,`CostPrice`,`Netto`,`Stock`,ProdUnit.UnitName AS Unit FROM `Products` "
                    + "INNER JOIN ProdUnit ON Products.UnitID = ProdUnit.UnitID ORDER BY Products.ProductID ASC";
            JRDesignQuery jQuery = new JRDesignQuery();
            jQuery.setText(sql);
            JasperDesign jDesign = JRXmlLoader.load(System.getProperty("user.dir") + "/src/com/resources/jrxml/RptStokBarang.jrxml");
            jDesign.setQuery(jQuery);
            JasperReport jReport = JasperCompileManager.compileReport(jDesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, new ConfigDB().getConnection());
            JRViewer jView = new JRViewer(jPrint);
            pnUmum.setLayout(new BorderLayout());
            jView.setFitPageZoomRatio();
            jView.setFont(new java.awt.Font("Arial", 0, 14));
            pnUmum.add(jView);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Pada:\n" + ex.toString(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void RptStockLimit() {
        try {
            jPanel1.removeAll();
            jPanel1.repaint();
            jPanel1.revalidate();
            String sql = "SELECT `ProdName`,`SellPrice`,`CostPrice`,`Netto`,`Stock`,ProdUnit.UnitName AS Unit FROM `Products` "
                    + "INNER JOIN ProdUnit ON Products.UnitID = ProdUnit.UnitID WHERE `Stock` <5";
            JRDesignQuery jQuery = new JRDesignQuery();
            jQuery.setText(sql);
            JasperDesign jDesign = JRXmlLoader.load(System.getProperty("user.dir") + "/src/com/resources/jrxml/RptStokBarangLimit.jrxml");
            jDesign.setQuery(jQuery);
            JasperReport jReport = JasperCompileManager.compileReport(jDesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, new ConfigDB().getConnection());
            JRViewer jView = new JRViewer(jPrint);
            jPanel1.setLayout(new BorderLayout());
            jView.setFitPageZoomRatio();
            jView.setFont(new java.awt.Font("Arial", 0, 14));
            jPanel1.add(jView);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Pada:\n" + ex.toString(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void RptStockOver() {
        try {
            jPanel2.removeAll();
            jPanel2.repaint();
            jPanel2.revalidate();
            String sql = "SELECT `ProdName`,`SellPrice`,`CostPrice`,`Netto`,`Stock`,ProdUnit.UnitName AS Unit "
                    + "FROM `Products` INNER JOIN ProdUnit ON Products.UnitID = ProdUnit.UnitID WHERE `Stock` >50";
            JRDesignQuery jQuery = new JRDesignQuery();
            jQuery.setText(sql);
            JasperDesign jDesign = JRXmlLoader.load(System.getProperty("user.dir") + "/src/com/resources/jrxml/RptStokBarangOver.jrxml");
            jDesign.setQuery(jQuery);
            JasperReport jReport = JasperCompileManager.compileReport(jDesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, new ConfigDB().getConnection());
            JRViewer jView = new JRViewer(jPrint);
            jPanel2.setLayout(new BorderLayout());
            jView.setFitPageZoomRatio();
            jView.setFont(new java.awt.Font("Arial", 0, 14));
            jPanel2.add(jView);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Pada:\n" + ex.toString(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void RptPriceList() {
        try {
            jPanel4.removeAll();
            jPanel4.repaint();
            jPanel4.revalidate();
            String sql = "SELECT DISTINCT ProdName,SellPrice FROM Products";
            JRDesignQuery jQuery = new JRDesignQuery();
            jQuery.setText(sql);
            JasperDesign jDesign = JRXmlLoader.load(System.getProperty("user.dir") + "/src/com/resources/jrxml/PriceList.jrxml");
            jDesign.setQuery(jQuery);
            JasperReport jReport = JasperCompileManager.compileReport(jDesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, null, new ConfigDB().getConnection());
            JRViewer jView = new JRViewer(jPrint);
            jPanel4.setLayout(new BorderLayout());
            jView.setFitPageZoomRatio();
            jView.setFont(new java.awt.Font("Arial", 0, 14));
            jPanel4.add(jView);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Pada:\n" + ex.toString(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void showAllReport() {
        RptStockItem();
        RptStockLimit();
        RptStockOver();
        RptPriceList();
    }
}
