/*
 * Copyright (C) 2020 flash
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.pointofsales.swing.manager;

import com.pointofsales.config.controller.CAdmin;
import com.pointofsales.config.database.ConfigDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author flash
 */
public class ViewAdmin extends javax.swing.JDialog {

    /**
     * Creates new form ViewProducts
     *
     * @param parent
     * @param modal
     */
    public ViewAdmin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        conn = new ConfigDB().getConnection();
        showRole();
        showGender();
        initForms();

    }
    private final Connection conn;
    private PreparedStatement pst;
    private ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNL = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEMail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNoTelp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<String>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        cmbJKelamin = new javax.swing.JComboBox<String>();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem1");
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem1");
        jPopupMenu1.add(jMenuItem3);
        jPopupMenu1.add(jSeparator2);

        jMenuItem4.setText("jMenuItem1");
        jPopupMenu1.add(jMenuItem4);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel3.setText("Nama Lengkap :");

        txtNL.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel4.setText("J. Kelamin :");

        txtEMail.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel5.setText("E-Mail :");

        txtNoTelp.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel6.setText("No. Telp :");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel7.setText("Alamat :");

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel9.setText("Role :");

        cmbRole.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cmbRole.setMaximumRowCount(5);
        cmbRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Pilih Role>" }));
        cmbRole.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbRolePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        cmbJKelamin.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cmbJKelamin.setMaximumRowCount(5);
        cmbJKelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<Pilih Data>" }));
        cmbJKelamin.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbJKelaminPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel8.setText("Password :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbRole, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbJKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNoTelp))
                    .addComponent(txtNL)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                    .addComponent(txtEMail)
                    .addComponent(jPasswordField1))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbJKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(104, 104, 104))
        );

        jTabbedPane1.addTab("Entry Data", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField1.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel2.setText("Cari Data :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jTabbedPane1.addTab("View Data", jPanel2);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/icon/icons8-management-48.png"))); // NOI18N
        jLabel1.setText("CRUD Data Admin");

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton1.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButton4.setText("Simpan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int questions = JOptionPane.showConfirmDialog(null, "Keluar Dari Menu Ini..?", "Perhatian", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (questions == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTable1.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Data Tidak Dipilih");
        } else {
            int questions = JOptionPane.showConfirmDialog(null, (String) jTable1.getValueAt(jTable1.getSelectedRow(), 2) + " Ini Akan Dihapus..?", "Perhatian", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (questions == JOptionPane.YES_OPTION) {
                cp.delItem((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
                initForms();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus...");
                tableRenderer();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTable1.getSelectedRow() == 0) {
            JOptionPane.showMessageDialog(this, "Data Harus Dipilih Dulu.");
        } else if (txtNL.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Lengkap Harus Diisi");
            txtNL.requestFocus();
        } else if (cmbJKelamin.getSelectedItem().equals("<Pilih Data>")) {
            JOptionPane.showMessageDialog(this, "Jenis Kelamin Harus Diisi");
            cmbJKelamin.requestFocus();
        } else if (txtNoTelp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No. Telepon Harus Diisi");
            txtNoTelp.requestFocus();
        } else if (txtAlamat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Alamat Harus Harus Diisi");
            txtAlamat.requestFocus();
        } else if (cmbRole.getSelectedItem() == "<Pilih Data>") {
            JOptionPane.showMessageDialog(this, "Satuan Barang Harus Diisi");
            cmbRole.requestFocus();
        } else {
            String AdminID = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            String FullName = txtNL.getText();
            String Phone = txtNoTelp.getText();
            String EMail = txtEMail.getText();
            String Address = txtAlamat.getText();
//            String Pass = jPasswordField1.getText();
//            Date td = new Date();
//            java.sql.Timestamp sqlTime = new java.sql.Timestamp(td.getTime());
            cp.editItem(AdminID, FullName, getGenderID(), Phone, EMail, Address, getRoleID());
            JOptionPane.showMessageDialog(null, "Data Telah Disimpan");
            initForms();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (txtNL.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Lengkap Harus Diisi");
            txtNL.requestFocus();
        } else if (cmbJKelamin.getSelectedItem().equals("<Pilih Data>")) {
            JOptionPane.showMessageDialog(this, "Jenis Kelamin Harus Diisi");
            cmbJKelamin.requestFocus();
        } else if (txtNoTelp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No. Telepon Harus Diisi");
            txtNoTelp.requestFocus();
        } else if (txtAlamat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Alamat Harus Harus Diisi");
            txtAlamat.requestFocus();
        } else if (cmbRole.getSelectedItem() == "<Pilih Data>") {
            JOptionPane.showMessageDialog(this, "Satuan Barang Harus Diisi");
            cmbRole.requestFocus();
        } else {
            String AdminID = null;
            String FullName = txtNL.getText();
            String Phone = txtNoTelp.getText();
            String EMail = txtEMail.getText();
            String Address = txtAlamat.getText();
            String Pass = jPasswordField1.getText();
            Date td = new Date();
            java.sql.Timestamp sqlTime = new java.sql.Timestamp(td.getTime());
            cp.addItem(AdminID, FullName, getGenderID(), Phone, EMail, Address, sqlTime, getRoleID(), Pass);
            JOptionPane.showMessageDialog(null, "Data Telah Disimpan");
            initForms();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cmbRolePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbRolePopupMenuWillBecomeInvisible
        getRoleID();
    }//GEN-LAST:event_cmbRolePopupMenuWillBecomeInvisible

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        getSelectedItem();
    }//GEN-LAST:event_jTable1MouseClicked

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoleActionPerformed

    private void cmbJKelaminPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbJKelaminPopupMenuWillBecomeInvisible
        getGenderID();
    }//GEN-LAST:event_cmbJKelaminPopupMenuWillBecomeInvisible

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased

    }//GEN-LAST:event_formMouseReleased

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JComboBox<String> cmbJKelamin;
    protected javax.swing.JComboBox<String> cmbRole;
    protected javax.swing.JButton jButton1;
    protected javax.swing.JButton jButton2;
    protected javax.swing.JButton jButton3;
    protected javax.swing.JButton jButton4;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JLabel jLabel2;
    protected javax.swing.JLabel jLabel3;
    protected javax.swing.JLabel jLabel4;
    protected javax.swing.JLabel jLabel5;
    protected javax.swing.JLabel jLabel6;
    protected javax.swing.JLabel jLabel7;
    protected javax.swing.JLabel jLabel8;
    protected javax.swing.JLabel jLabel9;
    protected javax.swing.JMenuItem jMenuItem1;
    protected javax.swing.JMenuItem jMenuItem2;
    protected javax.swing.JMenuItem jMenuItem3;
    protected javax.swing.JMenuItem jMenuItem4;
    protected javax.swing.JPanel jPanel1;
    protected javax.swing.JPanel jPanel2;
    protected javax.swing.JPasswordField jPasswordField1;
    protected javax.swing.JPopupMenu jPopupMenu1;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JScrollPane jScrollPane2;
    protected javax.swing.JSeparator jSeparator1;
    protected javax.swing.JPopupMenu.Separator jSeparator2;
    protected javax.swing.JTabbedPane jTabbedPane1;
    protected javax.swing.JTable jTable1;
    protected javax.swing.JTextField jTextField1;
    protected javax.swing.JTextArea txtAlamat;
    protected javax.swing.JTextField txtEMail;
    protected javax.swing.JTextField txtNL;
    protected javax.swing.JTextField txtNoTelp;
    // End of variables declaration//GEN-END:variables

    CAdmin cp = new CAdmin();

    private String getGenderID() {
        String genderID = null;
        try {
            String sql = "SELECT * FROM Gender WHERE GenderName = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, (String) cmbJKelamin.getSelectedItem());
            rs = pst.executeQuery();
            if (rs.next()) {
                genderID = rs.getString(1);
                System.out.println(genderID);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Pada: \n" + ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        return genderID;
    }

    private String getRoleID() {
        String roleID = null;
        try {
            String sql = "SELECT * FROM Role WHERE RoleName =?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, (String) cmbRole.getSelectedItem());
            rs = pst.executeQuery();
            if (rs.next()) {
                roleID = rs.getString(1);
                System.out.println(roleID);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Pada: \n" + ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        return roleID;
    }

    private void showGender() {
        try {
            String sql = "SELECT * FROM Gender";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                cmbJKelamin.addItem(rs.getString(2));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Pada: \n" + ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void showRole() {
        try {
            String sql = "SELECT * FROM Role";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while (rs.next()) {
                cmbRole.addItem(rs.getString(2));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Pada: \n" + ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void initForms() {
        jTable1.setModel(cp.model);
        cp.showDataItem();
        tableRenderer();
        txtNL.setText("");
        txtAlamat.setText("");
        cmbRole.setSelectedItem("");
        txtEMail.setText("");
        txtEMail.setText("");
        txtNoTelp.setText("");
        cmbRole.setSelectedItem("<Pilih Role>");
        cmbJKelamin.setSelectedItem("<Pilih Data>");
    }

    private void tableRenderer() {
        jTable1.setFont(new java.awt.Font("Liberation Sans", 0, 15));
        jTable1.getTableHeader().setSize(20, 30);
        jTable1.setRowHeight(23);
        jTable1.getTableHeader().setFont(new java.awt.Font("Liberation Sans", 0, 15));
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(290);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(155);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(255);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(250);
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(100);
    }

    private void getSelectedItem() {
        try {
            String sql = "Select * From Admin where AdminID = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, (String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            rs = pst.executeQuery();
            if (rs.next()) {
                txtNL.setText(rs.getString(2));
                txtAlamat.setText(rs.getString(6));
                txtEMail.setText(rs.getString(5));
                txtNoTelp.setText(rs.getString(4));
                cmbJKelamin.setSelectedItem((String) jTable1.getValueAt(jTable1.getSelectedRow(), 2));
                cmbRole.setSelectedItem((String) jTable1.getValueAt(jTable1.getSelectedRow(), 6));
                getGenderID();
                getRoleID();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Pada: \n" + ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private String getImagesAndURL() {
        String url = null;
        return url;
    }
}
