/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pointofsales.swing.utility;

import com.pointofsales.config.controller.UIConfig;
import com.pointofsales.config.database.ConfigDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Properties;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UnsupportedLookAndFeelException;

public class FLogin extends javax.swing.JFrame {

    private final Connection conn;

    /**
     * Creates new form FLogin
     *
     * @throws java.text.ParseException
     */
    public FLogin() throws ParseException {
        initComponents();
        openForm();
        conn = new ConfigDB().getConnection();
    }
    int count = 0;
    private SimpleDateFormat kal, time;
    private PreparedStatement pst;
    private ResultSet rs;
    private final ImageIcon icon = new ImageIcon("src/com/resources/icon/icons8-warning-48.png");
    private final ImageIcon iconBroken = new ImageIcon("src/com/resources/icon/icons8-broken-robot-60.png");
    private final FMainMenu mainMenu = new FMainMenu();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(116, 185, 198));
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/icon/icons8-computer-48.png"))); // NOI18N
        jLabel1.setText("Login");
        jLabel1.setName("jLabel1"); // NOI18N

        jPanel2.setBackground(new java.awt.Color(43, 207, 201));
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Admin :");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Password :");
        jLabel3.setName("jLabel3"); // NOI18N

        jButton1.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/icon/icons8-cancel-48 (1).png"))); // NOI18N
        jButton1.setText("Batal");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPasswordField1.setName("jPasswordField1"); // NOI18N

        jTextField1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField1.setToolTipText("Masukan Nama Anda");
        jTextField1.setName("jTextField1"); // NOI18N

        jButton2.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/icon/icons8-ok-48.png"))); // NOI18N
        jButton2.setText("Masuk");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jCheckBox1.setBackground(new java.awt.Color(43, 207, 201));
        jCheckBox1.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jCheckBox1.setText("Tampilkan Kata Sandi");
        jCheckBox1.setName("jCheckBox1"); // NOI18N
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel3)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jPanel2Layout.createSequentialGroup()
                                .add(0, 0, Short.MAX_VALUE)
                                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jPanel2Layout.createSequentialGroup()
                                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 398, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jPasswordField1))
                        .add(29, 29, 29))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jCheckBox1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(140, 140, 140))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jPasswordField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jCheckBox1)
                .add(13, 13, 13)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        authLogin();
        //checkLogin();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if (jCheckBox1.isSelected()) {
            jPasswordField1.setEchoChar((char) 0);
        } else {
            jPasswordField1.setEchoChar('•');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     * @throws javax.swing.UnsupportedLookAndFeelException
     * @throws java.text.ParseException
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException, ParseException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Properties props = new Properties();
        props.put("logoString", "");
//        props.put("selectionBackgroundColor", "180 240 197");
//        props.put("menuSelectionBackgroundColor", "180 240 197");
//
//        props.put("controlColor", "218 254 230");
//        props.put("controlColorLight", "218 254 230");
//        props.put("controlColorDark", "180 240 197");
//
//        props.put("buttonColor", "218 230 254");
//        props.put("buttonColorLight", "255 255 255");
//        props.put("buttonColorDark", "244 242 232");
// 
//        props.put("rolloverColor", "218 254 230");
//        props.put("rolloverColorLight", "218 254 230");
//        props.put("rolloverColorDark", "180 240 197");
//
//        props.put("windowTitleForegroundColor", "0 0 0");
//        props.put("windowTitleBackgroundColor", "180 240 197");
//        props.put("windowTitleColorLight", "218 254 230");
//        props.put("windowTitleColorDark", "180 240 197");
//        props.put("windowBorderColor", "218 254 230");
//        MintLookAndFeel.setCurrentTheme(props);

        UIConfig.setLookAndFeelConfig();
        try {
            FLogin dialog = new FLogin();
            dialog.setVisible(true);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Pada:\n" + ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JCheckBox jCheckBox1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPasswordField jPasswordField1;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void openForm() {
        this.setTitle("Login Form");
        // this.setIconImage(getToolkit().getImage("src/com/resources/icon//icons8-online-store-100.png"));
        this.jTextField1.setText("Sergey Dmitriev");
        this.jPasswordField1.setText("514785628");
    }
    Date date = new Date();

    private void authLogin() {
        count += 1;
        java.util.Date tgl = new Date();
        kal = new SimpleDateFormat("EEEE, d MMMM, y");
        time = new SimpleDateFormat("HH:mm:ss z");
        if (count > 4) {
            JOptionPane.showMessageDialog(this, "Anda Telah Gagal Login Sebanyak " + count + " Kali.\n"
                    + "Sistem Kami Mengira Anda Akan Meretas Sistem Kami.\n"
                    + "Sistem Akan Dihancurkan", "Ancaman Ditemukan..!!!", JOptionPane.ERROR_MESSAGE, iconBroken);
            this.setVisible(false);
            System.exit(0);
        } else {
            if (jTextField1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Silakan Isi Nama Admin Anda ...!", "Error", JOptionPane.ERROR_MESSAGE, icon);
                jTextField1.requestFocus();
            } else if (jPasswordField1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Silakan Isi Password Anda ...!", "Error", JOptionPane.ERROR_MESSAGE, icon);
                jPasswordField1.requestFocus();
            } else {
                try {
                    String sql = "SELECT * FROM `Admin` WHERE `FullName` = ? AND `Password` = ?";
                    pst = conn.prepareStatement(sql);
                    pst.setString(1, jTextField1.getText());
                    pst.setString(2, jPasswordField1.getText());
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        authUserPrivillege();
                        mainMenu.jLabel2.setText("Admin : " + rs.getString(2));
                        mainMenu.jLabel5.setText("Tanggal : " + time.format(date));
                        mainMenu.setExtendedState(JFrame.MAXIMIZED_BOTH);
                        mainMenu.setTitle("Point Of Sales");
                        // m.setIconImage(getToolkit().getImage("src/com/resources/icon/icons8-online-store-100.png"));
                        mainMenu.setVisible(true);
                        this.setVisible(false);
                    } else {
                        JOptionPane.showMessageDialog(this, "Nama Anda Dan Password Tidak Cocok ..!",
                                "Error", JOptionPane.ERROR_MESSAGE, icon);
                        jTextField1.setText("");
                        jPasswordField1.setText("");
                    }
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Terjadi Error Pada :\n" + ex.toString(),
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }

    private void authUserPrivillege() {
        try {
            if (rs.getString(8).equals("4")) {
                mainMenu.jMenu2.setEnabled(false);
            } else if (!rs.getString(8).equals("1")) {
                mainMenu.jMenu1.setEnabled(false);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi Error Pada :\n" + ex.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

}
