/*
 * Copyright 2020 :Karunia Awal Ramadhan <ayuwokibyytess@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.pointofsales.swing.transaction.orders;

import com.pointofsales.config.database.ConfigDB;
import com.pointofsales.swing.transaction.SelectSupplier;
import com.jgoodies.looks.plastic.PlasticXPLookAndFeel;
import com.jgoodies.looks.plastic.theme.ExperienceBlue;
import com.pointofsales.config.aom.DialogMessage;
import com.pointofsales.swing.transaction.sales.Invoices;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Time;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author :Karunia Awal Ramadhan <ayuwokibyytess@gmail.com>
 */
public class FOrders extends javax.swing.JDialog {

    ConfigDB db;

    /**
     * Creates new form FTransaction
     *
     * @param parent
     * @param modal
     */
    public FOrders(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        db = new ConfigDB();
        dm = new DialogMessage();
        decimalFormat();
        tableRenderer();
        openConnection();
        openForms();
    }
    Connection conn;
    PreparedStatement pst;
    Statement st;
    ResultSet rs;
    DecimalFormat df;
    DecimalFormatSymbols dfs;
    int discID, supplierID;
    public int empID;
    String unitItem, itemID;
    Date td = new Date();
    SimpleDateFormat fm = new SimpleDateFormat("yyyy-MM-dd");
    SimpleDateFormat formBulan = new SimpleDateFormat("MMMM");
    SimpleDateFormat formTahun = new SimpleDateFormat("yyyy");
    DialogMessage dm;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtKasir = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNoStruk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jXDatePicker1 = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtSubtotal = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtIdSupplier = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNamaSupplier = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtKontak = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtIdBarang = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtNamaBarang = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        txtDiscPersen = new javax.swing.JTextField();
        txtHargaJual = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txtHasilDiskon = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/icon/icons8-buying-30.png"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel2.setText("Menu Transaksi Pembelian Barang");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Menu Transaksi Pembelian Barang");
        jLabel3.setName("jLabel3"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 317, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail Pembelian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel4.setName("jPanel4"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Kasir :");
        jLabel4.setName("jLabel4"); // NOI18N

        txtKasir.setEditable(false);
        txtKasir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtKasir.setName("txtKasir"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("No. Struk :");
        jLabel5.setName("jLabel5"); // NOI18N

        txtNoStruk.setEditable(false);
        txtNoStruk.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNoStruk.setName("txtNoStruk"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Tanggal :");
        jLabel6.setName("jLabel6"); // NOI18N

        jXDatePicker1.setName("jXDatePicker1"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(jLabel5)
                    .add(jLabel6))
                .add(18, 18, 18)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(txtKasir, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .add(txtNoStruk)))
                    .add(jXDatePicker1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(546, 546, 546))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(txtKasir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(txtNoStruk, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jXDatePicker1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID. Barang", "Nama", "Jumlah", "Satuan", "Harga Jual", "Diskon", "Total"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setName("jTable1"); // NOI18N
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Subtotal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N

        txtSubtotal.setFont(new java.awt.Font("Arial", 0, 70)); // NOI18N
        txtSubtotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSubtotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtSubtotal.setName("txtSubtotal"); // NOI18N
        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(txtSubtotal)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(txtSubtotal)
                .add(4, 4, 4))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Supplier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel5.setName("jPanel5"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("ID. Supplier :");
        jLabel7.setName("jLabel7"); // NOI18N

        txtIdSupplier.setEditable(false);
        txtIdSupplier.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        txtIdSupplier.setName("txtIdSupplier"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Nama :");
        jLabel9.setName("jLabel9"); // NOI18N

        txtNamaSupplier.setEditable(false);
        txtNamaSupplier.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaSupplier.setName("txtNamaSupplier"); // NOI18N
        txtNamaSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaSupplierActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Kontak :");
        jLabel11.setName("jLabel11"); // NOI18N

        txtKontak.setEditable(false);
        txtKontak.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtKontak.setName("txtKontak"); // NOI18N
        txtKontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKontakActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setText("Cari");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel7)
                    .add(jLabel9)
                    .add(jLabel11))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel5Layout.createSequentialGroup()
                        .add(txtIdSupplier, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(txtNamaSupplier)
                    .add(txtKontak))
                .add(557, 557, 557))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(txtIdSupplier, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel7)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(txtNamaSupplier, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(txtKontak, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail Barang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel6.setName("jPanel6"); // NOI18N

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("ID. Barang :");
        jLabel14.setName("jLabel14"); // NOI18N

        txtIdBarang.setEditable(false);
        txtIdBarang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIdBarang.setName("txtIdBarang"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Nama :");
        jLabel15.setName("jLabel15"); // NOI18N

        txtNamaBarang.setEditable(false);
        txtNamaBarang.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtNamaBarang.setName("txtNamaBarang"); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Stok :");
        jLabel16.setName("jLabel16"); // NOI18N

        txtStok.setEditable(false);
        txtStok.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtStok.setEnabled(false);
        txtStok.setName("txtStok"); // NOI18N

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Cari");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Harga Beli :");
        jLabel17.setName("jLabel17"); // NOI18N

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("Diskon :");
        jLabel18.setName("jLabel18"); // NOI18N

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("Quantity :");
        jLabel19.setName("jLabel19"); // NOI18N

        txtQty.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtQty.setName("txtQty"); // NOI18N
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtyKeyTyped(evt);
            }
        });

        txtDiscPersen.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDiscPersen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDiscPersen.setEnabled(false);
        txtDiscPersen.setName("txtDiscPersen"); // NOI18N

        txtHargaJual.setEditable(false);
        txtHargaJual.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtHargaJual.setName("txtHargaJual"); // NOI18N

        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setText("Ok");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtHasilDiskon.setEditable(false);
        txtHasilDiskon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtHasilDiskon.setEnabled(false);
        txtHasilDiskon.setName("txtHasilDiskon"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel14)
                    .add(jLabel15)
                    .add(jLabel16))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(txtNamaBarang)
                    .add(txtStok)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel6Layout.createSequentialGroup()
                        .add(txtIdBarang, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel17)
                    .add(jLabel18)
                    .add(jLabel19))
                .add(18, 18, 18)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(txtDiscPersen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 47, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(txtHasilDiskon))
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(txtQty, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 68, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(txtHargaJual))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(txtIdBarang, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton1)
                    .add(jLabel17)
                    .add(txtHargaJual, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel15)
                    .add(txtNamaBarang, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel18)
                    .add(txtDiscPersen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtHasilDiskon, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel16)
                    .add(txtStok, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel19)
                    .add(txtQty, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton2))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setName("jPanel3"); // NOI18N

        jButton7.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jButton7.setText("Keluar ");
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        jButton8.setText("Print ");
        jButton8.setName("jButton8"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jButton8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton7))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jButton7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jButton8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton9.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/icon/icons8-bill-48.png"))); // NOI18N
        jButton9.setText("Bayar");
        jButton9.setName("jButton9"); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/resources/icon/icons8-synchronize-48.png"))); // NOI18N
        jButton5.setText("Baru");
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 366, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jScrollPane1)
                    .add(layout.createSequentialGroup()
                        .add(jPanel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 366, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jButton9)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 114, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE, false)
                    .add(jButton5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jButton9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        openForms();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int result = JOptionPane.showConfirmDialog(null, "Batalkan Barang " + jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString() + "..?", "Perhatian", JOptionPane.OK_CANCEL_OPTION);
        if (evt.getClickCount() == 1) {
            if (result == JOptionPane.OK_OPTION) {
                model.removeRow(jTable1.getSelectedRow());
                getCountSubtotal();
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        authPayment();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void txtNamaSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaSupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaSupplierActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        selectItem();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        selectSuppliers();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        insertDataIntoTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtKontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKontakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKontakActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (txtSubtotal.getText().equalsIgnoreCase("0.00")) {
            dm.showInformationMessage("Transaksi Tidak Ada\nBukti Pembayaran Mungkin Tidak Dapat Ditampilkan");
        } else {
            printSalesInvoices();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void txtQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtQtyKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.swingx.JXDatePicker jXDatePicker1;
    private javax.swing.JTextField txtDiscPersen;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextField txtHasilDiskon;
    private javax.swing.JTextField txtIdBarang;
    private javax.swing.JTextField txtIdSupplier;
    public javax.swing.JTextField txtKasir;
    private javax.swing.JTextField txtKontak;
    private javax.swing.JTextField txtNamaBarang;
    private javax.swing.JTextField txtNamaSupplier;
    private javax.swing.JTextField txtNoStruk;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtSubtotal;
    // End of variables declaration//GEN-END:variables
    private void openConnection() {
        conn = db.getConnection();
    }

    private void createColumnsOnTable() {
        jTable1.setModel(new DefaultTableModel(null, new String[]{"ID. Barang", "Nama Barang", "Jumlah", "Satuan", "Harga Beli", "Total"}));
        tableRenderer();
        startTimer();
    }
    int autoNumber, hJual, qty, diskon, hTotal;

    private void openForms() {
        createColumnsOnTable();
        txtSubtotal.setEditable(false);
        txtSubtotal.setText("Rp. 0.00");
        txtIdBarang.setText("");
        txtNamaBarang.setText("");
        txtStok.setText("");
        txtDiscPersen.setText("");
        txtHargaJual.setText("");
        txtHasilDiskon.setText("");
        txtQty.setText("");
        jXDatePicker1.setFont(new java.awt.Font("Liberation Sans", 0, 14));
        txtSubtotal.setFont(new java.awt.Font("Liberation Sans", 0, 75));
        jXDatePicker1.setDate(td);
        jXDatePicker1.setFormats("dd-MM-yyyy");
        txtNoStruk.setText(Integer.toString(getBillNumber()));
        this.autoNumber = getBillNumber();
    }

    private void tableRenderer() {
        jTable1.setFont(new Font("Arial", 0, 15));
        jTable1.getTableHeader().setSize(20, 30);
        jTable1.setRowHeight(24);
        jTable1.getTableHeader().setFont(new java.awt.Font("Arial", 0, 15));
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(99);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(450);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(87);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(87);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(160);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(235);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setResizable(false);
        jTable1.getColumnModel().getColumn(4).setResizable(false);
        jTable1.getColumnModel().getColumn(5).setResizable(false);
    }
    String satuan = null;

    private void insertDataIntoTable() {
        if (txtIdBarang.getText().isEmpty() || txtQty.getText().isEmpty()) {
            dm.showWarningMessage("Data Barang Tidak Ada..!\nSilakan Pilih Data Barang Terlebih Dahulu..");
        } else {
            hJual = Integer.parseInt(txtHargaJual.getText());
            qty = Integer.parseInt(txtQty.getText());
            hTotal = hJual * qty;
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{txtIdBarang.getText(), txtNamaBarang.getText(), txtQty.getText(), satuan, txtHargaJual.getText(),
                hTotal});
            cleanFieldAfterInsertListIntoModel();
        }
    }

    private void CustNo() {
        try {
            int custno = 1;
            String sql = "select count(distinct OrderID)+1 from Orders";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.next();
            custno = rs.getInt(1);
            txtNoStruk.setText("ORD" + custno);
            rs.close();
        } catch (SQLException ex) {
            dm.showErrorMessage("Terjadi Error Pada:\n" + ex.toString());
        }
    }

    private void decimalFormat() {
        df = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        dfs = new DecimalFormatSymbols();
        dfs.setCurrencySymbol("");
        dfs.setMonetaryDecimalSeparator('.');
        dfs.setGroupingSeparator('.');
        df.setDecimalFormatSymbols(dfs);
    }

    private int getCountSubtotal() {
        int subTotals = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            subTotals = subTotals + Integer.parseInt(jTable1.getValueAt(i, 5).toString());
        }
        return subTotals;
    }

    private void saveDataPayment() {
        try {
            Time sqlTimes = new Time(td.getTime());
            String sql = "Insert Into Orders Values (?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtNoStruk.getText());
            pst.setString(2, fm.format(td));
            pst.setTime(3, sqlTimes);
            pst.setInt(4, empID);
            pst.setInt(5, supplierID);
            pst.setInt(6, getItemFreight());
            pst.setInt(7, getCountSubtotal());
            pst.executeUpdate();
            saveDataDetailPayment();
            updateItemStockWhenTransactionSuccess();
        } catch (SQLException ex) {
            dm.showErrorMessage("Terjadi Error Pada:\n" + ex.toString());
        }
    }
    Font font = new java.awt.Font("Arial", 0, 70);

    private void saveDataDetailPayment() {
        try {
            String sql = "Insert Into OrdersDetail Values (?,?,?,?)";
            pst = conn.prepareStatement(sql);
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                String NoJual = txtNoStruk.getText();
                String KodeBarang = jTable1.getValueAt(i, 0).toString();
                int Qty = Integer.parseInt(jTable1.getValueAt(i, 2).toString());
                int Total = Integer.parseInt(jTable1.getValueAt(i, 5).toString());
                pst.setString(1, NoJual);
                pst.setString(2, KodeBarang);
                pst.setInt(3, Qty);
                pst.setInt(4, Total);
                pst.executeUpdate();
            }
            pst.addBatch();
        } catch (SQLException ex) {
            dm.showErrorMessage("Terjadi Error Pada:\n" + ex.toString());
        }
    }

    private void updateItemStockWhenTransactionSuccess() {
        try {
            String sql = "Update Products Set Stock = Stock + ? Where ProductID = ?";
            pst = conn.prepareStatement(sql);
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                int oldValue = Integer.parseInt(jTable1.getValueAt(i, 2).toString());
                String idStock = jTable1.getValueAt(i, 0).toString();
                pst.setInt(1, oldValue);
                pst.setString(2, idStock);
                pst.executeUpdate();
            }
            pst.addBatch();
        } catch (SQLException ex) {
            dm.showErrorMessage("Terjadi Error Pada:\n" + ex.toString());
        }
    }

    private void updateStockIn() {
        try {
            String sql = "Update Products Set StockIn = ? Where ProductID = ?";
            pst = conn.prepareStatement(sql);
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                int oldValue = Integer.parseInt(jTable1.getValueAt(i, 2).toString());
                String idStock = jTable1.getValueAt(i, 0).toString();
                pst.setInt(1, oldValue);
                pst.setString(2, idStock);
                pst.executeUpdate();
            }
            pst.addBatch();
        } catch (SQLException ex) {
            dm.showErrorMessage("Terjadi Error Pada:\n" + ex.toString());
        }
    }

    private int getBillNumber() {
        int billNo = 1;
        try {
            pst = conn.prepareStatement("SELECT MAX(OrderID) FROM Orders");
            rs = pst.executeQuery();
            rs.next();
            billNo = rs.getInt(1) + 1;
            rs.close();
        } catch (SQLException ex) {
            dm.showErrorMessage("Terjadi Error Pada:\n" + ex.toString());
        }
        return billNo;
    }

    private int getItemFreight() {
        int total = 0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            total = total + Integer.parseInt(jTable1.getValueAt(i, 2).toString());
        }
        return total;
    }

    private void cleanFieldAfterInsertListIntoModel() {
        getCountSubtotal();
        System.out.println(getCountSubtotal());
        txtSubtotal.setText("Rp. " + df.format(getCountSubtotal()));
        getItemFreight();
        System.out.println(getItemFreight());
        txtIdBarang.setText("");
        txtNamaBarang.setText("");
        txtStok.setText("");
        txtHargaJual.setText("");
        txtQty.setText("");
    }

    private void selectItem() {
        try {
            ChooseProduct sp = new ChooseProduct(null, true);
            sp.setVisible(true);
            int b = sp.jTable1.getSelectedRow();
            String id = (String) sp.jTable1.getValueAt(b, 0);
            String nama = (String) sp.jTable1.getValueAt(b, 2);
            String hjual = (String) sp.jTable1.getValueAt(b, 4);
            String stok = (String) sp.jTable1.getValueAt(b, 6);
            String unitID = (String) sp.jTable1.getValueAt(b, 7);
            itemID = id;
            txtIdBarang.setText(id);
            txtNamaBarang.setText(nama);
            txtHargaJual.setText(hjual);
            txtStok.setText(stok);
            hJual = Integer.valueOf(hjual);
            qty = Integer.valueOf(stok);
            satuan = unitID;
            txtQty.requestFocus();
            sp.dispose();
        } catch (ArrayIndexOutOfBoundsException ex) {
            //JOptionPane.showMessageDialog(null, "Terjadi Error :\n"+ex.toString(),"Kesalahan",JOptionPane.ERROR_MESSAGE);
        }
    }

    private void selectSuppliers() {
        try {
            SelectSupplier sp = new SelectSupplier(null, true);
            sp.setVisible(true);
            int b = sp.jTable1.getSelectedRow();
            String id = (String) sp.jTable1.getValueAt(b, 0);
            String nama = (String) sp.jTable1.getValueAt(b, 1);
            String kontak = (String) sp.jTable1.getValueAt(b, 6);
            txtIdSupplier.setText(id);
            supplierID = Integer.parseInt(id);
            txtNamaSupplier.setText(nama);
            txtKontak.setText(kontak);
            sp.dispose();
        } catch (ArrayIndexOutOfBoundsException e) {
        }
    }

    protected void printSalesInvoices() {
        try {
            //int SaleID = autoNumber;
            HashMap nofa = new HashMap();
            nofa.put("OrderID", txtNoStruk.getText());
            String localePath = System.getProperty("user.dir") + "/src/com/resources/jrxml/OrderInvoices.jrxml";
            JasperDesign jDesign = JRXmlLoader.load(localePath);
            JasperReport jReport = JasperCompileManager.compileReport(jDesign);
            JasperPrint jPrint = JasperFillManager.fillReport(jReport, nofa, conn);
            JasperViewer jView = new JasperViewer(jPrint);
            //JasperPrintManager.printReport(jPrint, true);
            Invoices inv = new Invoices(null, true);
            inv.setContentPane(jView.getContentPane());
            inv.setSize(650, 500);
            inv.setLocationRelativeTo(null);
            inv.setTitle("Faktur Pembelian");
            inv.setResizable(false);
            jView.setFitPageZoomRatio();
            jView.setFitWidthZoomRatio();
            inv.setVisible(true);
        } catch (JRException ex) {
            dm.showErrorMessage("Tidak Dapat Menampilkan Hasil Struk\nTerjadi Error Pada:\n" + ex.toString());
        }
    }

    private void startTimer() {
        Timer updateTimer;
        int delay = 100;
        updateTimer = new Timer(delay, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date currentTime = new Date();
                String formatTimeStr = "HH:mm:ss z";
                String formatDate = "EEEE, d MMMM yyyy";
                DateFormat formatTime = new SimpleDateFormat(formatTimeStr);
                DateFormat formatDay = new SimpleDateFormat(formatDate);
                String formattedTimeStr = formatTime.format(currentTime);
                jLabel3.setText("Pukul : " + formattedTimeStr);
                //  jLabel5.setText("Hari, Tanggal : " + formatDay.format(currentTime));
            }
        });
        updateTimer.start();
    }

    private void authPayment() {
        if (txtSubtotal.getText().equalsIgnoreCase("Rp. 0.00") || txtIdSupplier.getText().isEmpty()
                || txtKasir.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Transaksi Pembelian Tidak Ada..!", "Perhatian", JOptionPane.WARNING_MESSAGE);
        } else {
            saveDataPayment();
            JOptionPane.showMessageDialog(null, "Data Disimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            //openForms();
        }
    }
}
